const express = require('express');
const nodemailer = require('nodemailer');
const dotenv = require('dotenv');
const cors = require('cors');
const path = require('path');

// Load environment variables from src/.env
dotenv.config({ path: path.join(__dirname, 'src', '.env') });

const app = express();
const PORT = process.env.PORT || 5501;

// Middleware
app.use(cors());
app.use(express.json());

// Serve static files from the 'src' directory
app.use(express.static(path.join(__dirname, 'src')));

// Helper to sanitize environment variables (removes potential duplicated prefix e.g. "SMTP_HOST=smtp.gmail.com")
function getEnv(key) {
    let val = process.env[key];
    if (!val) return '';
    val = val.trim();
    const prefix = `${key}=`;
    if (val.startsWith(prefix)) {
        return val.substring(prefix.length).trim();
    }
    const prefixWithSpace = `${key} =`;
    if (val.startsWith(prefixWithSpace)) {
        const parts = val.split('=');
        parts.shift();
        return parts.join('=').trim();
    }
    return val;
}

const smtpHost = getEnv('SMTP_HOST');
const smtpPort = parseInt(getEnv('SMTP_PORT') || '587', 10);
const smtpUser = getEnv('SMTP_USER');
const smtpPass = getEnv('SMTP_PASS');
const adminEmail = getEnv('ADMIN_EMAIL') || 'mr.ganeshkumar999@gmail.com';

// Transporter configuration for nodemailer
const transporter = nodemailer.createTransport({
    host: smtpHost,
    port: smtpPort,
    secure: smtpPort === 465, // true for 465, false for other ports
    auth: {
        user: smtpUser,
        pass: smtpPass
    }
});

// Endpoint to send email notifications
app.post('/api/send-email', async (req, res) => {
    try {
        const {
            fullName,
            whatsapp,
            email,
            city,
            age,
            status,
            income,
            experience,
            purchasedCourse,
            problems,
            goal,
            invest,
            source,
            availability
        } = req.body;

        // Construct simple HTML notification content
        const htmlContent = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 25px; border: 1px solid #ddd; border-radius: 10px; background-color: #fafafa; text-align: center;">
                <h2 style="color: #D4AF37; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; margin-bottom: 20px;">Clarity Session Request</h2>
                <p style="font-size: 16px; color: #333; line-height: 1.5; margin-bottom: 25px;">
                    Hello Admin,<br><br>
                    A new user has just submitted a request for a <strong>1:1 Clarity Session</strong> on the PrimeVerse Portal.
                </p>
                <p style="font-size: 14px; color: #666; margin-top: 20px; font-style: italic;">
                    Please log into your Supabase dashboard to view their complete details and review the application.
                </p>
                <div style="margin-top: 35px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 15px;">
                    This notification was automatically generated by the PrimeVerse Portal.
                </div>
            </div>
        `;

        const mailOptions = {
            from: `"PrimeVerse Portal" <${smtpUser}>`,
            to: adminEmail,
            subject: `🚨 A user has requested a 1:1 Clarity Session`,
            html: htmlContent
        };

        const info = await transporter.sendMail(mailOptions);
        console.log('Email sent successfully:', info.messageId);
        res.status(200).json({ success: true, message: 'Email sent successfully' });
    } catch (error) {
        console.error('Error sending email:', error);
        res.status(500).json({ success: false, message: 'Failed to send email', error: error.message });
    }
});

app.listen(PORT, () => {
    console.log(`Server is running on http://localhost:${PORT}`);
});
