const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');
const nodemailer = require('nodemailer');

// Load environment variables from any of the potential .env locations
const possiblePaths = [
    path.join(__dirname, '..', 'src', '.env'),
    path.join(__dirname, '..', '.env'),
    path.join(__dirname, '.env')
];

for (const envPath of possiblePaths) {
    if (fs.existsSync(envPath)) {
        dotenv.config({ path: envPath });
        break;
    }
}

// Helper to sanitize environment variables (removes potential duplicated prefix e.g. "SMTP_HOST=smtp.gmail.com")
function getEnv(key) {
    let val = process.env[key];
    if (!val) return '';
    val = val.trim();
    const prefix = `${key}=`;
    if (val.startsWith(prefix)) {
        return val.substring(prefix.length).trim();
    }
    const prefixWithSpace = `${key} =`;
    if (val.startsWith(prefixWithSpace)) {
        const parts = val.split('=');
        parts.shift();
        return parts.join('=').trim();
    }
    return val;
}

module.exports = async (req, res) => {
    // Add CORS headers for Vercel
    res.setHeader('Access-Control-Allow-Credentials', true);
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS,PATCH,DELETE,POST,PUT');
    res.setHeader(
        'Access-Control-Allow-Headers',
        'X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version'
    );

    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ message: 'Method Not Allowed' });
    }

    try {
        const smtpHost = getEnv('SMTP_HOST');
        const smtpPort = parseInt(getEnv('SMTP_PORT') || '587', 10);
        const smtpUser = getEnv('SMTP_USER');
        const smtpPass = getEnv('SMTP_PASS');
        const adminEmail = getEnv('ADMIN_EMAIL') || 'mr.ganeshkumar999@gmail.com';

        // Retrieve SMTP settings from Vercel environment variables
        const transporter = nodemailer.createTransport({
            host: smtpHost,
            port: smtpPort,
            secure: false, // true for 465, false for other ports
            auth: {
                user: smtpUser,
                pass: smtpPass
            }
        });

        // Construct simple HTML notification content
        const htmlContent = `
            <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto; padding: 25px; border: 1px solid #ddd; border-radius: 10px; background-color: #fafafa; text-align: center;">
                <h2 style="color: #D4AF37; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; margin-bottom: 20px;">Clarity Session Request</h2>
                <p style="font-size: 16px; color: #333; line-height: 1.5; margin-bottom: 25px;">
                    Hello Admin,<br><br>
                    A new user has just submitted a request for a <strong>1:1 Clarity Session</strong> on the PrimeVerse Portal.
                </p>
                <p style="font-size: 14px; color: #666; margin-top: 20px; font-style: italic;">
                    Please log into your Supabase dashboard to view their complete details and review the application.
                </p>
                <div style="margin-top: 35px; text-align: center; font-size: 12px; color: #888; border-top: 1px solid #eee; padding-top: 15px;">
                    This notification was automatically generated by the PrimeVerse Portal.
                </div>
            </div>
        `;

        const mailOptions = {
            from: `"PrimeVerse Portal" <${smtpUser}>`,
            to: adminEmail,
            subject: `🚨 A user has requested a 1:1 Clarity Session`,
            html: htmlContent
        };

        const info = await transporter.sendMail(mailOptions);
        console.log('Email sent successfully:', info.messageId);
        return res.status(200).json({ success: true, message: 'Email sent successfully' });
    } catch (error) {
        console.error('Error sending email:', error);
        return res.status(500).json({ success: false, message: 'Failed to send email', error: error.message });
    }
};
